### ISSUE TITLE
Default content is breaking drush installation from configuration.

### ISSUE THREAD

**Issue by damontgomery** [acquia/reservoir#33]
Steps to reproduce:
- Install the reservoir site with drush `drush si reservoir`
- Export the configuration (no changes made) with drush `drush cex`
- Attempt to reinstall the site from configuration `drush si reservoir --config-dir="../config/default"`

```
Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization. in            [error]
Drupal\Core\Config\ConfigImporter->validate() (line 728 of
/var/www/well/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php).
The import failed due for the following reasons:                                                                   [error]
Entities exist of type <em class="placeholder">Taxonomy term</em> and <em class="placeholder">Vocabulary</em>
<em class="placeholder">Tags</em>. These entities need to be deleted before importing.
Entities exist of type <em class="placeholder">Content</em> and <em class="placeholder">Content type</em> <em
class="placeholder">Article</em>. These entities need to be deleted before importing.
```

Possible fix:
Don't create default nodes and terms. See below for relevant code. When I remove those lines, everything works fine, although there is no demo content. :)

Suggested long term fix:
Maybe if you go through the UI, provide an option to create default roles / permissions / content. By default, don't create any of this. The site recommends against keeping these long term anyway.

Possible causes:
I believe the way drush does the site install is that it first does a normal site install which generates it's own site ID. This will be different than the one previously exported. Then, drush updates the new site's key to match exported configuration. Then, because all the configuration files loaded have different keys than those exported, it basically deletes them all and reloads from the files. It cannot delete the configuration files around article nodes and tags terms because Reservoir has created content.

Acquia BLT uses the site install as a core piece of it's local development and testing and this is causing issues with those.

Relevant code:
`reservoir.install` hook `reservoir_install()`
```
  // Create default content.
  file_unmanaged_copy(\Drupal::root() . '/' . drupal_get_path('profile', 'reservoir') . '/reservoir-logo.png', 'public://reservoir-logo.png');
  $file = File::create(['uri' => 'public://reservoir-logo.png']);
  $file->save();
  $term = Term::create([
    'name' => 'Camelids',
    'vid' => 'tags',
  ]);
  $term->save();
  Node::create([
    'type' => 'article',
    'field_body' => [
      'value' => 'The name "llama" was adopted by European settlers from native Peruvians.',
      'format' => 'basic_html',
    ],
    'field_image' => [
      [
        'alt' => 'Reservoir logo: a "pancake stack" with layers of water instead of pancakes, to reference Drupal!',
        'title' => 'Reservoir logo',
        'target_id' => $file->id(),
      ],
    ],
    'field_tags' => [
      [
        'target_id' => $term->id(),
      ],
    ],
  ])
    ->setTitle('Hello world!')
    ->setOwnerId(1)
    ->save();
```

**Comment by wimleers** [comment]
Closing this in favor of #54 (which would solve this direct problem) and #47 (which discusses the broader problem).
