### ISSUE TITLE
Reservoir for production?

### ISSUE THREAD

**Issue by fabdelgado** [acquia/reservoir#34]
I'm thinking about reservoir for production, I do not want to risk it until it's not ready.
What is the estimated time to be released in beta?

**Comment by wimleers** [comment]
I think the answer is:

> Ready when it's ready

Also, "beta" does not mean "production-ready".

I wish I could give you a timeframe, but that's impossible. We're working on many of the upstream projects that Reservoir bundles together. Expect lots of improvements in the weeks and months to come! That's I think the best, most accurate, fairest answer I can give at the moment :)

**Comment by fabdelgado** [comment]
Thanks!
