### ISSUE TITLE
CORS configuration has no effect when using default services.yml

### ISSUE THREAD

**Issue by danepowell** [acquia/reservoir#55]
#29 intended to allow cross-origin requests out of the box by adding CORS settings to reservoir.services.yml. This is a great idea, but unfortunately I don't think it will have any effect on most installs.

The problem is that the [default.services.yml](http://cgit.drupalcode.org/drupal/tree/sites/default/default.services.yml#n161) file provided by Drupal core disables CORS by default, and this takes precedence over the configuration provided by Reservoir. Any site that's using a `services.yml` file copied from `default.services.yml` (i.e. most sites?) will need to modify this file--CORS won't work out of the box as intended.

At the least, it would be good to document this in the Reservoir README. But there might be other ways to force the service definition to take effect and work out of the box.

**Comment by Decipher** [comment]
So CORs is enabled and configured in `reservoir.services.yml`, so I suspect this issue should be closed now.

**Comment by tedbow** [comment]
Yep think this is fixed
