### ISSUE TITLE
Lightning combined with Reservoir

### ISSUE THREAD

**Issue by simesy** [acquia/reservoir#64]
acquia/lightning requires a similar (but different) combination of components to Reservoir, and in fact there is a conflict if you try to use some combinations of Reservior and Lightning in the same composer.json. Do you consider Reservoir tools to be redundant if we're using Lightning?

If Reservoir does some special things that Lightning doesn't (and lets ignore the customized reservoir UI, let's just focus on API tools) - then if a client wants the Lightning editor experience in their headless Drupal, how would you recommend combining them together?

I'm not adverse to patching one or the other (eg with composer)  to make them work together, but I want to see if there's an official way.

For those watching at home, the overlap is in:
drupal/jsonapi
drupal/openapi
drupal/simple_oauth

**Comment by simesy** [comment]
Now I see
https://www.drupal.org/node/2896267
https://github.com/acquia/lightning/blob/8.x-2.x/README.md#api-first

Which I think essentially makes Reservoir redundant when using Lightning?

**Comment by tedbow** [comment]
Yeah, I think you would want to choose 1 or the other.

Sorry I don't think we want to support the combo
