### ISSUE TITLE
Composer  install crashes on Install -- "Killed" before completing build

### ISSUE THREAD

**Issue by vveerrgg** [acquia/reservoir#65]
Trying a default install on a MyPHPadmin server _(512 MB Memory / 20 GB Disk / SGP1 - Ubuntu PhpMyAdmin on 16.04)_ 

Using the following command it crashes trying to retrieve / write the config.json file.

`composer create-project acquia/reservoir-project _*myproject_name*_ --stability=alpha -vvv`

...
```
Reading /root/.cache/composer/repo/https---packagist.org/provider-drupal$views-ui.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-drupal$workflows.json from cache
Reading /root/.cache/composer/repo/https---packages.drupal.org-8/provider-drupal$media.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-drupal$media.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-drupal$settings-tray.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-drupal$core-class-finder.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$expression-language.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$config.json from cache
Killed
```

Not sure how to get past this bug, nor where to look for a more detailed log...  I also tried installing on a fresh Ubuntu build and it still breaks.

Suggestions on how to get past this error?

**Comment by chris-hamper** [comment]
Composer is VERY memory hungry; it's quite likely that 512MB of RAM simply isn't enough for the `composer create-project` to succeed. As a workaround, you can try running that command on your local computer and zipping/tarballing/git repo-ing the entire resulting install over to the server (**including** the vendor directories).

If you really don't want to commit the `vendor` directory, you may be able to run the `composer create-project` on a local machine and commit the resulting install minus the `vendor` directory, but being sure to include the `composer.lock` file in the commit. Checking that out on the server and running `composer install` may work with less memory usage.

**Comment by tedbow** [comment]
Closing this if no more feedback.
