### ISSUE TITLE
Integrate Reservoir with search

### ISSUE THREAD

**Issue by gollyg** [acquia/reservoir#66]
_As a site user I want to be able to search content so that I kind find information relevant to my needs_

It would be great to be able to expose a new endpoint that integrates with Drupal search. The standard way of doing this in Drupal may be exposing a searchapi view to REST, but this does not fit with the approach taken by Reservoir, so there may be a more elegant way of achieving this.

**Comment by tedbow** [comment]
You can search content by using filters in jsonapi module.
https://www.drupal.org/docs/8/modules/json-api/filtering

We don't have plans to enable the REST module.
