### ISSUE TITLE
Cannot access API documentation

### ISSUE THREAD

**Issue by damontgomery** [acquia/reservoir#7]
Version: Alpha 1

Go to:
admin/api
admin/api/config

Get error:
```
Oops... ReDoc failed to render this spec
Error downloading http://local.well.com/admin/whoops HTTP ERROR 404
```

This happens on any of the API pages.

**Comment by damontgomery** [comment]
This is no longer an issue after re-installing and reconfiguring composer.

**Comment by wimleers** [comment]
Glad you figured it out :)
