### ISSUE TITLE
Cannot assign roles to Clients

### ISSUE THREAD

**Issue by damontgomery** [acquia/reservoir#8]
Version: Alpha 1

As I understand it, I create a User (or use one) and that user has roles. Then I create clients for that user and the client has it's own roles? Then I can use that client.

I cannot assign roles to a client using the Demo App client and I don't see any way to link the user to the client. The `demo-writer` user doesn't have any configuration pointing to the client and neither does the client.

See the screenshot below which shows only `Label`, `Secret`, and `Is Confidential` are values on the client.

![edit_client___well](https://user-images.githubusercontent.com/397902/27344594-7ee0ef66-55ac-11e7-9588-2dab55239480.jpg)

**Comment by damontgomery** [comment]
I was able to resolve this by following the steps here #9.

Basically, create a new role first and then you can assign scope to those clients.

**Comment by tedbow** [comment]
@damontgomery thanks for filing these issues.

Re-opening to see if we need better help text and/or need file an issue against the related modules for better help text.

**Comment by wimleers** [comment]
Fixed by #10.
